### ISSUE TITLE
Another link for trained model

### ISSUE THREAD

**Issue by park2j** [yxlijun/Pyramidbox.pytorch#4]
Thanks a lot yxlijun.
Your work has helped me a lot with my project.
I tried to download trained model for running demo.py
But it seems I can't get to baidu drive.
Uploading to ex)google drive will be very helpful.

**Comment by yxlijun** [comment]
you can down model in https://drive.google.com/open?id=1130vivAWuG1VTn8dlVpSXENbVWn5xVHQ

**Comment by park2j** [comment]
Thanks for the link !!!!!!
